name: todo
description: ''
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  drift: ^2.25.1
  drift_flutter: ^0.2.4
  uuid: ^4.5.1
  path: ^1.9.1
  path_provider: ^2.1.5
  freezed: ^3.0.3
  freezed_annotation: ^3.0.0
  collection: ^1.19.1
  flutter_bloc: ^9.1.0
  timeago: ^3.7.0
  timeago_flutter: ^3.7.0
  supabase_flutter: ^2.8.4
  shared_preferences: ^2.5.2
  async: ^2.12.0
  go_router: ^14.8.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.25.2
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true